<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PrintHubWindowsClient-c00a5c4d-ceab-479a-ac06-5327e0f2a20e</UserSecretsId>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="AppConfig\Sample_appSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PdfiumViewer.Native.x86_64.no_v8-no_xfa" Version="2018.4.8.256" />
    <PackageReference Include="PdfiumViewer.Updated" Version="2.14.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Therefore\Enums\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="AppConfig\Sample_appSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Temp\.readme">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
